// package main contains the entrypoint for the gomock deleter tool
package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/cccteam/ccc/pkg"
	"github.com/go-playground/errors/v5"
)

const generationComment = "// Code generated by MockGen. DO NOT EDIT"

func main() {
	pkgInfo, err := pkg.Info()
	if err != nil {
		log.Fatal(err)
	}

	if err := filepath.WalkDir(pkgInfo.AbsolutePath, deleteMockFiles()); err != nil {
		fmt.Println(err)
	}
}

func deleteMockFiles() func(path string, d os.DirEntry, err error) error {
	return func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !d.IsDir() && filepath.Ext(path) == ".go" {
			file, err := os.Open(path)
			if err != nil {
				return errors.Wrap(err, "os.Open()")
			}
			defer file.Close()

			text := make([]byte, len(generationComment))
			if _, err := file.Read(text); err != nil {
				return errors.Wrap(err, "file.Read()")
			}

			if strings.Contains(string(text), generationComment) {
				if err := file.Close(); err != nil {
					return errors.Wrap(err, "file.Close()")
				}

				if err := os.Remove(path); err != nil {
					return errors.Wrap(err, "os.Remove()")
				}
			}
		}

		return nil
	}
}
