// Code generated by resourcegeneration. DO NOT EDIT.
import { FieldName, Method, Resource } from '@cccteam/ccc-lib';
import { Meta, ValidRPCTypes } from '@components/Resource/resources-helpers';
import { Methods } from './zz_gen_constants';

export interface FieldPointer {
  field: FieldName;
}

export interface PostPaymentsConfig {
  personId: string | FieldPointer;
  payments: string[] | FieldPointer;
  id: string | FieldPointer;
}
export interface PostPayments {
  personId: string;
  payments: string[];
  id: string;
}

export interface RPCFieldMeta {
  fieldName: string;
  displayType: ValidRPCTypes;
  enumeratedResource?: Resource;
}

export interface MethodMeta {
  route: string;
  fields: RPCFieldMeta[];
}

export type MethodMap = Record<Method, MethodMeta>;

const methodMap: MethodMap = {
  [Methods.PostPayments]: {
    route: 'post-payments',
    fields: [
      { fieldName: 'personId', displayType: 'string' },
      { fieldName: 'payments', displayType: 'string[]' },
      { fieldName: 'id', displayType: 'uuid' },
    ],
  },
};

export function methodMeta(method: Method): Meta {
  if (methodMap[method] !== undefined) {
    return methodMap[method];
  } else {
    console.error('Method not found in methodMap:', method);
    return {} as Meta;
  }
}
