// Code generated by resourcegeneration. DO NOT EDIT.
import { Domain, FieldName, Method, Permission, Resource } from '@cccteam/ccc-lib';

export const Permissions = {
  Create: 'Create' as Permission,
  Delete: 'Delete' as Permission,
  Execute: 'Execute' as Permission,
  List: 'List' as Permission,
  Read: 'Read' as Permission,
  Update: 'Update' as Permission,
};

export const Domains = {
  global: 'global' as Domain,
};

export const Resources = {
  Users: 'Users' as Resource,
  Weathers: 'Weathers' as Resource,
};

export const Methods = {
  PostPayments: 'PostPayments' as Method,
};


export namespace Users {
  export const fieldName = {
    id: 'id' as FieldName,
    username: 'username' as FieldName,
  };
  export const resourceName = {
    id: 'Users.id' as Resource,
    username: 'Users.username' as Resource,
  };
};

export namespace Weathers {
  export const fieldName = {
    loanId: 'loanId' as FieldName,
    personAddressId: 'personAddressId' as FieldName,
  };
  export const piiFieldName = {
    temperature: 'temperature' as FieldName,
  };
  export const resourceName = {
    loanId: 'Weathers.loanId' as Resource,
    personAddressId: 'Weathers.personAddressId' as Resource,
    temperature: 'Weathers.temperature' as Resource,
  };
};


export namespace PostPayments {
  export const fieldName = {
    personId: 'personId' as FieldName,
    payments: 'payments' as FieldName,
    id: 'id' as FieldName,
  };
};

type ResourcePermissions = Record<Permission, boolean>;
type PermissionMappings = Record<Resource, ResourcePermissions>;

const Mappings: PermissionMappings = {
  [Resources.Users]: {
    [Permissions.Create]: true,
    [Permissions.Delete]: true,
    [Permissions.List]: true,
    [Permissions.Read]: true,
    [Permissions.Update]: true,
  },
  [Users.resourceName.id]: {
    [Permissions.Create]: false,
    [Permissions.Delete]: false,
    [Permissions.List]: false,
    [Permissions.Read]: false,
    [Permissions.Update]: false,
  },
  [Users.resourceName.username]: {
    [Permissions.Create]: false,
    [Permissions.Delete]: false,
    [Permissions.List]: false,
    [Permissions.Read]: false,
    [Permissions.Update]: false,
  },
  [Resources.Weathers]: {
    [Permissions.Create]: false,
    [Permissions.Delete]: false,
    [Permissions.List]: true,
    [Permissions.Read]: true,
    [Permissions.Update]: false,
  },
  [Weathers.resourceName.loanId]: {
    [Permissions.Create]: false,
    [Permissions.Delete]: false,
    [Permissions.List]: false,
    [Permissions.Read]: false,
    [Permissions.Update]: false,
  },
  [Weathers.resourceName.personAddressId]: {
    [Permissions.Create]: false,
    [Permissions.Delete]: false,
    [Permissions.List]: false,
    [Permissions.Read]: false,
    [Permissions.Update]: false,
  },
  [Weathers.resourceName.temperature]: {
    [Permissions.Create]: false,
    [Permissions.Delete]: false,
    [Permissions.List]: false,
    [Permissions.Read]: false,
    [Permissions.Update]: false,
  },
};

export function requiresPermission(resource: Resource, permission: Permission): boolean {
  return Mappings[resource]?.[permission] ?? false;
}

type MethodPermissions = Record<Permission, boolean>;
type MethodPermissionMappings = Record<Method, MethodPermissions>;

const MethodMappings: MethodPermissionMappings = {
  [Methods.PostPayments]: {
    [Permissions.Execute]: true,
  },
};

export function requiresMethodPermission(resource: Method, permission: Permission): boolean {
  return MethodMappings[resource]?.[permission] ?? false;
}
