// Code generated by resourcegeneration. DO NOT EDIT.
import { Resource } from '@cccteam/ccc-lib';
import { ResourceMap, ResourceMeta } from '@components/Resource/resources-helpers';
import { Resources } from './zz_gen_constants';

export interface Users {
  id: string;
  username: string;
}

export interface Weathers {
  loanId: string;
  personAddressId: string;
  temperature: number;
}

const resourceMap: ResourceMap = {
  [Resources.Users]: {
    route: 'users',
    consolidatedRoute: 'resources',
    fields: [
      { fieldName: 'id', primaryKey: { ordinalPosition: 0 }, displayType: 'uuid', required: false, isIndex: true },
      { fieldName: 'username', displayType: 'string', required: true, isIndex: false },
    ],
  },
  [Resources.Weathers]: {
    route: 'weathers',createDisabled: true, updateDisabled: true, deleteDisabled: true,
    fields: [
      { fieldName: 'loanId', primaryKey: { ordinalPosition: 0 }, displayType: 'string', required: true, isIndex: false },
      { fieldName: 'personAddressId', displayType: 'string', required: false, isIndex: false },
      { fieldName: 'temperature', displayType: 'number', required: false, isIndex: false },
    ],
  },
}

export function resourceMeta(resource: Resource): ResourceMeta {
  if (resourceMap[resource] !== undefined) {
    return resourceMap[resource];
  } else {
    console.error('Resource not found in resourceMap:', resource);
    return {} as ResourceMeta;
  }
}
