name: Feature
description: Create a feature
labels: feature
type: feature
title: '[Feature] <feature name>'
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the feature. Click the `Paste, drop, or click to add files` button below the input box to attach any relevant mockups/requirements.
      placeholder: This feature is to...
    validations:
      required: true
  - type: markdown
    attributes:
      value: '**_To add tasks to this feature, please add them as sub-issues ([docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues)), after creating this feature._**'
  - type: markdown
    attributes:
      value: ''
