// Code generated by resourcegeneration. DO NOT EDIT.
// Source: ./pkg/resources

package app

import (
	"net/http"
	"time"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/demo-app/pkg/rpc"
	"github.com/cccteam/httpio"
	"github.com/shopspring/decimal"
	"go.opentelemetry.io/otel"
)

func (a *App) PostPayments() http.HandlerFunc {
	type payment struct {
		Date   time.Time       `json:"date"`
		Amount decimal.Decimal `json:"amount"`
		Note   string          `json:"note"`
	}

	type request struct {
		PersonID string    `json:"personId"`
		Payments []payment `json:"payments"`
		ID       ccc.UUID  `json:"id"`
	}

	decoder := NewRPCDecoder[rpc.PostPayments, request](a, accesstypes.Execute)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := otel.Tracer(name).Start(r.Context(), "App.PostPayments()")
		defer span.End()

		params, err := decoder.Decode(r)
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		p := &rpc.PostPayments{
			PersonID: params.PersonID,
			ID:       params.ID,
		}
		for _, e := range params.Payments {
			p.Payments = append(p.Payments, rpc.Payment(e))
		}
		if err := p.Execute(ctx, a.ResourceClient(), a.RPCClient()); err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		return httpio.NewEncoder(w).Ok(nil)
	})
}
