// Code generated by resourcegeneration. DO NOT EDIT.
// Source: ./pkg/resources

package app

import (
	"net/http"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/demo-app/pkg/resources"
	"github.com/cccteam/demo-app/pkg/router"
	"github.com/cccteam/httpio"
	"go.opentelemetry.io/otel"
)

func (a *App) Users() http.HandlerFunc {
	type user struct {
		Id       ccc.UUID `json:"id"       index:"true"`
		Username string   `json:"username"`
	}

	type response []map[string]interface{}

	decoder := NewQueryDecoder[resources.User, user](a, accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := otel.Tracer(name).Start(r.Context(), "App.Users()")
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewUserQueryFromQuerySet(querySet)

		resp := response{}
		for r, err := range res.Query().List(ctx, a.ResourceClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*user)(r)
			rmap := make(map[string]interface{})
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "Id":
					rmap["id"] = rec.Id
				case "Username":
					rmap["username"] = rec.Username
				}
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}

func (a *App) User() http.HandlerFunc {
	type response struct {
		Id       ccc.UUID `json:"id"       index:"true"`
		Username string   `json:"username"`
	}

	decoder := NewQueryDecoder[resources.User, response](a, accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := otel.Tracer(name).Start(r.Context(), "App.User()")
		defer span.End()

		id := httpio.Param[ccc.UUID](r, router.UserID)

		querySet, err := decoder.Decode(r, a.UserPermissions(r))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		res := resources.NewUserQueryFromQuerySet(querySet).SetId(id)

		row, err := res.Query().Read(ctx, a.ResourceClient())
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(row)
		rmap := make(map[string]interface{})
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "Id":
				rmap["id"] = rec.Id
			case "Username":
				rmap["username"] = rec.Username
			}
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
