// Code generated by resourcegeneration. DO NOT EDIT.
// Source: ./pkg/resources

package app

import (
	"net/http"

	"github.com/cccteam/ccc"
	"github.com/cccteam/ccc/accesstypes"
	"github.com/cccteam/demo-app/pkg/computedresources"
	"github.com/cccteam/demo-app/pkg/router"
	"github.com/cccteam/httpio"
	"go.opentelemetry.io/otel"
)

func (a *App) Weathers() http.HandlerFunc {
	type weather struct {
		LoanID          ccc.UUID `json:"loanId"`
		PersonAddressID ccc.UUID `json:"personAddressId"`
		Temperature     float32  `json:"temperature"     pii:"true"`
	}

	type response []map[string]any

	decoder := NewQueryDecoder[computedresources.Weather, weather](a, accesstypes.List)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := otel.Tracer(name).Start(r.Context(), "App.Weathers()")
		defer span.End()

		querySet, err := decoder.Decode(r, a.UserPermissions(r))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		resp := response{}
		for r, err := range computedresources.ListWeather(ctx, querySet, a.ResourceClient(), a.ComputedClient()) {
			if err != nil {
				return httpio.NewEncoder(w).ClientMessage(ctx, err)
			}
			rec := (*weather)(r)
			rmap := make(map[string]any)
			for _, field := range querySet.Fields() {
				switch string(field) {
				case "LoanID":
					rmap["loanId"] = rec.LoanID
				case "PersonAddressID":
					rmap["personAddressId"] = rec.PersonAddressID
				case "Temperature":
					rmap["temperature"] = rec.Temperature
				}
			}
			resp = append(resp, rmap)
		}

		return httpio.NewEncoder(w).Ok(resp)
	})
}
func (a *App) Weather() http.HandlerFunc {
	type response struct {
		LoanID          ccc.UUID `json:"loanId"`
		PersonAddressID ccc.UUID `json:"personAddressId"`
		Temperature     float32  `json:"temperature"     pii:"true"`
	}

	decoder := NewQueryDecoder[computedresources.Weather, response](a, accesstypes.Read)

	return httpio.Log(func(w http.ResponseWriter, r *http.Request) error {
		ctx, span := otel.Tracer(name).Start(r.Context(), "App.Weather()")
		defer span.End()

		loanID := httpio.Param[ccc.UUID](r, router.WeatherLoanID)

		querySet, err := decoder.Decode(r, a.UserPermissions(r))
		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}

		row, err := computedresources.ReadWeather(ctx, loanID, querySet, a.ResourceClient(), a.ComputedClient())

		if err != nil {
			return httpio.NewEncoder(w).ClientMessage(ctx, err)
		}
		rec := (*response)(row)
		rmap := make(map[string]any)
		for _, field := range querySet.Fields() {
			switch string(field) {
			case "LoanID":
				rmap["loanId"] = rec.LoanID
			case "PersonAddressID":
				rmap["personAddressId"] = rec.PersonAddressID
			case "Temperature":
				rmap["temperature"] = rec.Temperature
			}
		}

		return httpio.NewEncoder(w).Ok(rmap)
	})
}
