// Code generated by resourcegeneration. DO NOT EDIT.
// Source: ./pkg/resources

package app

import (
	"github.com/cccteam/ccc/resource"
	"github.com/cccteam/demo-app/pkg/computedresources"
	"github.com/cccteam/demo-app/pkg/resources"
)

type Resourcer interface {
	resource.Resourcer
	resources.User | computedresources.Weather
}
