// Code generated by resourcegeneration. DO NOT EDIT.
// Source: ./pkg/resources

package rpc

import "github.com/cccteam/ccc/accesstypes"

type Method interface {
	Method() accesstypes.Resource
	PostPayments
}
