// Code generated by MockGen. DO NOT EDIT.
// Source: ../../pkg/router/router.go
//
// Generated by this command:
//
//	mockgen -source ../../pkg/router/router.go -destination ../../pkg/mock/mock_router/mock_handlers.go
//

// Package mock_router is a generated GoMock package.
package mock_router

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHandlers is a mock of Handlers interface.
type MockHandlers struct {
	ctrl     *gomock.Controller
	recorder *MockHandlersMockRecorder
	isgomock struct{}
}

// MockHandlersMockRecorder is the mock recorder for MockHandlers.
type MockHandlersMockRecorder struct {
	mock *MockHandlers
}

// NewMockHandlers creates a new mock instance.
func NewMockHandlers(ctrl *gomock.Controller) *MockHandlers {
	mock := &MockHandlers{ctrl: ctrl}
	mock.recorder = &MockHandlersMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandlers) EXPECT() *MockHandlersMockRecorder {
	return m.recorder
}

// Assets mocks base method.
func (m *MockHandlers) Assets() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Assets")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Assets indicates an expected call of Assets.
func (mr *MockHandlersMockRecorder) Assets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Assets", reflect.TypeOf((*MockHandlers)(nil).Assets))
}

// Authenticated mocks base method.
func (m *MockHandlers) Authenticated() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Authenticated")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Authenticated indicates an expected call of Authenticated.
func (mr *MockHandlersMockRecorder) Authenticated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Authenticated", reflect.TypeOf((*MockHandlers)(nil).Authenticated))
}

// CallbackOIDC mocks base method.
func (m *MockHandlers) CallbackOIDC() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CallbackOIDC")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// CallbackOIDC indicates an expected call of CallbackOIDC.
func (mr *MockHandlersMockRecorder) CallbackOIDC() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CallbackOIDC", reflect.TypeOf((*MockHandlers)(nil).CallbackOIDC))
}

// CompressionMiddleware mocks base method.
func (m *MockHandlers) CompressionMiddleware() func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompressionMiddleware")
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// CompressionMiddleware indicates an expected call of CompressionMiddleware.
func (mr *MockHandlersMockRecorder) CompressionMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompressionMiddleware", reflect.TypeOf((*MockHandlers)(nil).CompressionMiddleware))
}

// DeepLink mocks base method.
func (m *MockHandlers) DeepLink(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeepLink", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// DeepLink indicates an expected call of DeepLink.
func (mr *MockHandlersMockRecorder) DeepLink(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeepLink", reflect.TypeOf((*MockHandlers)(nil).DeepLink), next)
}

// FrontChannelLogout mocks base method.
func (m *MockHandlers) FrontChannelLogout() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FrontChannelLogout")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// FrontChannelLogout indicates an expected call of FrontChannelLogout.
func (mr *MockHandlersMockRecorder) FrontChannelLogout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FrontChannelLogout", reflect.TypeOf((*MockHandlers)(nil).FrontChannelLogout))
}

// LoggerMiddleware mocks base method.
func (m *MockHandlers) LoggerMiddleware() func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoggerMiddleware")
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// LoggerMiddleware indicates an expected call of LoggerMiddleware.
func (mr *MockHandlersMockRecorder) LoggerMiddleware() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoggerMiddleware", reflect.TypeOf((*MockHandlers)(nil).LoggerMiddleware))
}

// Login mocks base method.
func (m *MockHandlers) Login() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Login indicates an expected call of Login.
func (mr *MockHandlersMockRecorder) Login() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockHandlers)(nil).Login))
}

// Logout mocks base method.
func (m *MockHandlers) Logout() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockHandlersMockRecorder) Logout() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockHandlers)(nil).Logout))
}

// NoCaching mocks base method.
func (m *MockHandlers) NoCaching(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NoCaching", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// NoCaching indicates an expected call of NoCaching.
func (mr *MockHandlersMockRecorder) NoCaching(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoCaching", reflect.TypeOf((*MockHandlers)(nil).NoCaching), next)
}

// PatchResources mocks base method.
func (m *MockHandlers) PatchResources() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchResources")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// PatchResources indicates an expected call of PatchResources.
func (mr *MockHandlersMockRecorder) PatchResources() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchResources", reflect.TypeOf((*MockHandlers)(nil).PatchResources))
}

// PostPayments mocks base method.
func (m *MockHandlers) PostPayments() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostPayments")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// PostPayments indicates an expected call of PostPayments.
func (mr *MockHandlersMockRecorder) PostPayments() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostPayments", reflect.TypeOf((*MockHandlers)(nil).PostPayments))
}

// SecurityHeaders mocks base method.
func (m *MockHandlers) SecurityHeaders(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SecurityHeaders", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// SecurityHeaders indicates an expected call of SecurityHeaders.
func (mr *MockHandlersMockRecorder) SecurityHeaders(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SecurityHeaders", reflect.TypeOf((*MockHandlers)(nil).SecurityHeaders), next)
}

// SetSessionTimeout mocks base method.
func (m *MockHandlers) SetSessionTimeout(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSessionTimeout", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// SetSessionTimeout indicates an expected call of SetSessionTimeout.
func (mr *MockHandlersMockRecorder) SetSessionTimeout(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSessionTimeout", reflect.TypeOf((*MockHandlers)(nil).SetSessionTimeout), next)
}

// SetXSRFToken mocks base method.
func (m *MockHandlers) SetXSRFToken(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetXSRFToken", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// SetXSRFToken indicates an expected call of SetXSRFToken.
func (mr *MockHandlersMockRecorder) SetXSRFToken(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetXSRFToken", reflect.TypeOf((*MockHandlers)(nil).SetXSRFToken), next)
}

// StartSession mocks base method.
func (m *MockHandlers) StartSession(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSession", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// StartSession indicates an expected call of StartSession.
func (mr *MockHandlersMockRecorder) StartSession(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSession", reflect.TypeOf((*MockHandlers)(nil).StartSession), next)
}

// User mocks base method.
func (m *MockHandlers) User() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "User")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// User indicates an expected call of User.
func (mr *MockHandlersMockRecorder) User() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "User", reflect.TypeOf((*MockHandlers)(nil).User))
}

// Users mocks base method.
func (m *MockHandlers) Users() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Users")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Users indicates an expected call of Users.
func (mr *MockHandlersMockRecorder) Users() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Users", reflect.TypeOf((*MockHandlers)(nil).Users))
}

// ValidateSession mocks base method.
func (m *MockHandlers) ValidateSession(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSession", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateSession indicates an expected call of ValidateSession.
func (mr *MockHandlersMockRecorder) ValidateSession(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSession", reflect.TypeOf((*MockHandlers)(nil).ValidateSession), next)
}

// ValidateXSRFToken mocks base method.
func (m *MockHandlers) ValidateXSRFToken(next http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateXSRFToken", next)
	ret0, _ := ret[0].(http.Handler)
	return ret0
}

// ValidateXSRFToken indicates an expected call of ValidateXSRFToken.
func (mr *MockHandlersMockRecorder) ValidateXSRFToken(next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateXSRFToken", reflect.TypeOf((*MockHandlers)(nil).ValidateXSRFToken), next)
}

// Weather mocks base method.
func (m *MockHandlers) Weather() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Weather")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Weather indicates an expected call of Weather.
func (mr *MockHandlersMockRecorder) Weather() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Weather", reflect.TypeOf((*MockHandlers)(nil).Weather))
}

// Weathers mocks base method.
func (m *MockHandlers) Weathers() http.HandlerFunc {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Weathers")
	ret0, _ := ret[0].(http.HandlerFunc)
	return ret0
}

// Weathers indicates an expected call of Weathers.
func (mr *MockHandlersMockRecorder) Weathers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Weathers", reflect.TypeOf((*MockHandlers)(nil).Weathers))
}

// WithParamsHTTP mocks base method.
func (m *MockHandlers) WithParamsHTTP() func(http.Handler) http.Handler {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithParamsHTTP")
	ret0, _ := ret[0].(func(http.Handler) http.Handler)
	return ret0
}

// WithParamsHTTP indicates an expected call of WithParamsHTTP.
func (mr *MockHandlersMockRecorder) WithParamsHTTP() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithParamsHTTP", reflect.TypeOf((*MockHandlers)(nil).WithParamsHTTP))
}
