-- GENERATED BY SCHEMA GEN. DO NOT EDIT.
CREATE TABLE Sessions (
  Id STRING(36) NOT NULL,
  OidcSid STRING(36) NOT NULL,
  Username STRING(MAX) NOT NULL,
  CreatedAt TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true),
  UpdatedAt TIMESTAMP OPTIONS (allow_commit_timestamp=true),
  Expired BOOL NOT NULL,

  CONSTRAINT CK_Sessions_Id CHECK (REGEXP_CONTAINS(Id, r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')),
  CONSTRAINT CK_Sessions_OidcSid CHECK (REGEXP_CONTAINS(OidcSid, r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$')),
) PRIMARY KEY (Id), ROW DELETION POLICY (OLDER_THAN(CreatedAt, INTERVAL 30 DAY));

CREATE  INDEX SessionsByOidcSid ON Sessions(OidcSid);
CREATE  INDEX SessionsByUsername ON Sessions(Username);
CREATE  INDEX SessionsByExpired ON Sessions(Expired);