// Code generated by spannergen. DO NOT EDIT.
// Source: ./pkg/resources

package router

import (
	"net/http"

	"github.com/cccteam/httpio"
	"github.com/go-chi/chi/v5"
)

const (
	UserID        httpio.ParamType = "userID"
	WeatherLoanID httpio.ParamType = "weatherLoanID"
)

type GeneratedHandlers interface {
	PostPayments() http.HandlerFunc

	Users() http.HandlerFunc
	User() http.HandlerFunc

	Weathers() http.HandlerFunc
	Weather() http.HandlerFunc

	PatchResources() http.HandlerFunc
}

func generatedRoutes(r chi.Router, h GeneratedHandlers) {
	r.Post("/api/post-payments", h.PostPayments())

	usersHandler := h.Users()
	r.Get("/api/users", usersHandler)
	r.Post("/api/users", usersHandler)

	userHandler := h.User()
	r.Get("/api/users/{userID}", userHandler)
	r.Post("/api/users/{userID}", userHandler)

	weathersHandler := h.Weathers()
	r.Get("/api/weathers", weathersHandler)
	r.Post("/api/weathers", weathersHandler)

	weatherHandler := h.Weather()
	r.Get("/api/weathers/{weatherLoanID}", weatherHandler)
	r.Post("/api/weathers/{weatherLoanID}", weatherHandler)

	r.Patch("/api/resources", h.PatchResources())
}
