// Code generated by handlergen. DO NOT EDIT.
// Source: ./pkg/resources

package router

import (
	"net/http"

	"github.com/cccteam/demo-app/pkg/mock/mock_router"
)

type generatedRouterTest struct {
	url         string
	method      string
	handlerFunc string
	parameters  map[string]string
}

func generatedRouteParameters() []string {
	keys := []string{
		"userID",
		"weatherLoanID",
	}

	return keys
}

func generatedRouterTests() []*generatedRouterTest {
	routerTests := []*generatedRouterTest{
		{
			url: "/api/users", method: http.MethodGet,
			handlerFunc: "Users",
			parameters:  map[string]string{},
		},
		{
			url: "/api/users", method: http.MethodPost,
			handlerFunc: "Users",
			parameters:  map[string]string{},
		},
		{
			url: "/api/users/testUserID", method: http.MethodGet,
			handlerFunc: "User",
			parameters:  map[string]string{"userID": "testUserID"},
		},
		{
			url: "/api/users/testUserID", method: http.MethodPost,
			handlerFunc: "User",
			parameters:  map[string]string{"userID": "testUserID"},
		},
		{
			url: "/api/weathers", method: http.MethodGet,
			handlerFunc: "Weathers",
			parameters:  map[string]string{},
		},
		{
			url: "/api/weathers", method: http.MethodPost,
			handlerFunc: "Weathers",
			parameters:  map[string]string{},
		},
		{
			url: "/api/weathers/testWeatherLoanID", method: http.MethodGet,
			handlerFunc: "Weather",
			parameters:  map[string]string{"weatherLoanID": "testWeatherLoanID"},
		},
		{
			url: "/api/weathers/testWeatherLoanID", method: http.MethodPost,
			handlerFunc: "Weather",
			parameters:  map[string]string{"weatherLoanID": "testWeatherLoanID"},
		},
		{
			url: "/api/resources", method: http.MethodPatch,
			handlerFunc: "PatchResources",
		},
	}

	return routerTests
}

func generatedExpectCalls(e *mock_router.MockHandlersMockRecorder, rec *callRecorder) {
	e.PostPayments().Times(1).Return(rec.RecordHandlerCall("PostPayments"))
	e.Users().Times(1).Return(rec.RecordHandlerCall("Users"))
	e.User().Times(1).Return(rec.RecordHandlerCall("User"))
	e.Weathers().Times(1).Return(rec.RecordHandlerCall("Weathers"))
	e.Weather().Times(1).Return(rec.RecordHandlerCall("Weather"))
	e.PatchResources().Times(1).Return(rec.RecordHandlerCall("PatchResources"))
}
