// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cccteam/ccc/resource (interfaces: Reader)
//
// Generated by this command:
//
//	mockgen -destination=../../pkg/mock/mock_resource/mock_reader.go github.com/cccteam/ccc/resource Reader
//

// Package mock_resource is a generated GoMock package.
package mock_resource

import (
	context "context"
	iter "iter"
	reflect "reflect"

	resource "github.com/cccteam/ccc/resource"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader[Resource resource.Resourcer] struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder[Resource]
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder[Resource resource.Resourcer] struct {
	mock *MockReader[Resource]
}

// NewMockReader creates a new mock instance.
func NewMockReader[Resource resource.Resourcer](ctrl *gomock.Controller) *MockReader[Resource] {
	mock := &MockReader[Resource]{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder[Resource]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader[Resource]) EXPECT() *MockReaderMockRecorder[Resource] {
	return m.recorder
}

// DBType mocks base method.
func (m *MockReader[Resource]) DBType() resource.DBType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBType")
	ret0, _ := ret[0].(resource.DBType)
	return ret0
}

// DBType indicates an expected call of DBType.
func (mr *MockReaderMockRecorder[Resource]) DBType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBType", reflect.TypeOf((*MockReader[Resource])(nil).DBType))
}

// List mocks base method.
func (m *MockReader[Resource]) List(ctx context.Context, stmt *resource.Statement) iter.Seq2[*Resource, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, stmt)
	ret0, _ := ret[0].(iter.Seq2[*Resource, error])
	return ret0
}

// List indicates an expected call of List.
func (mr *MockReaderMockRecorder[Resource]) List(ctx, stmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReader[Resource])(nil).List), ctx, stmt)
}

// Read mocks base method.
func (m *MockReader[Resource]) Read(ctx context.Context, stmt *resource.Statement) (*Resource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", ctx, stmt)
	ret0, _ := ret[0].(*Resource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockReaderMockRecorder[Resource]) Read(ctx, stmt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReader[Resource])(nil).Read), ctx, stmt)
}
