// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cccteam/ccc/resource (interfaces: ReadWriteTransaction)
//
// Generated by this command:
//
//	mockgen -destination=../../pkg/mock/mock_resource/mock_read_write_transaction.go github.com/cccteam/ccc/resource ReadWriteTransaction
//

// Package mock_resource is a generated GoMock package.
package mock_resource

import (
	reflect "reflect"

	accesstypes "github.com/cccteam/ccc/accesstypes"
	resource "github.com/cccteam/ccc/resource"
	spxscan "github.com/cccteam/spxscan"
	gomock "go.uber.org/mock/gomock"
)

// MockReadWriteTransaction is a mock of ReadWriteTransaction interface.
type MockReadWriteTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockReadWriteTransactionMockRecorder
	isgomock struct{}
}

// MockReadWriteTransactionMockRecorder is the mock recorder for MockReadWriteTransaction.
type MockReadWriteTransactionMockRecorder struct {
	mock *MockReadWriteTransaction
}

// NewMockReadWriteTransaction creates a new mock instance.
func NewMockReadWriteTransaction(ctrl *gomock.Controller) *MockReadWriteTransaction {
	mock := &MockReadWriteTransaction{ctrl: ctrl}
	mock.recorder = &MockReadWriteTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadWriteTransaction) EXPECT() *MockReadWriteTransactionMockRecorder {
	return m.recorder
}

// BufferMap mocks base method.
func (m *MockReadWriteTransaction) BufferMap(res resource.PatchSetMetadata, patch map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BufferMap", res, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// BufferMap indicates an expected call of BufferMap.
func (mr *MockReadWriteTransactionMockRecorder) BufferMap(res, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufferMap", reflect.TypeOf((*MockReadWriteTransaction)(nil).BufferMap), res, patch)
}

// BufferStruct mocks base method.
func (m *MockReadWriteTransaction) BufferStruct(res resource.PatchSetMetadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BufferStruct", res)
	ret0, _ := ret[0].(error)
	return ret0
}

// BufferStruct indicates an expected call of BufferStruct.
func (mr *MockReadWriteTransactionMockRecorder) BufferStruct(res any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BufferStruct", reflect.TypeOf((*MockReadWriteTransaction)(nil).BufferStruct), res)
}

// DBType mocks base method.
func (m *MockReadWriteTransaction) DBType() resource.DBType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DBType")
	ret0, _ := ret[0].(resource.DBType)
	return ret0
}

// DBType indicates an expected call of DBType.
func (mr *MockReadWriteTransactionMockRecorder) DBType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DBType", reflect.TypeOf((*MockReadWriteTransaction)(nil).DBType))
}

// DataChangeEventIndex mocks base method.
func (m *MockReadWriteTransaction) DataChangeEventIndex(res accesstypes.Resource, rowID string) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DataChangeEventIndex", res, rowID)
	ret0, _ := ret[0].(int)
	return ret0
}

// DataChangeEventIndex indicates an expected call of DataChangeEventIndex.
func (mr *MockReadWriteTransactionMockRecorder) DataChangeEventIndex(res, rowID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DataChangeEventIndex", reflect.TypeOf((*MockReadWriteTransaction)(nil).DataChangeEventIndex), res, rowID)
}

// PostgresReadOnlyTransaction mocks base method.
func (m *MockReadWriteTransaction) PostgresReadOnlyTransaction() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostgresReadOnlyTransaction")
	ret0, _ := ret[0].(any)
	return ret0
}

// PostgresReadOnlyTransaction indicates an expected call of PostgresReadOnlyTransaction.
func (mr *MockReadWriteTransactionMockRecorder) PostgresReadOnlyTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostgresReadOnlyTransaction", reflect.TypeOf((*MockReadWriteTransaction)(nil).PostgresReadOnlyTransaction))
}

// SpannerReadOnlyTransaction mocks base method.
func (m *MockReadWriteTransaction) SpannerReadOnlyTransaction() spxscan.Querier {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpannerReadOnlyTransaction")
	ret0, _ := ret[0].(spxscan.Querier)
	return ret0
}

// SpannerReadOnlyTransaction indicates an expected call of SpannerReadOnlyTransaction.
func (mr *MockReadWriteTransactionMockRecorder) SpannerReadOnlyTransaction() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpannerReadOnlyTransaction", reflect.TypeOf((*MockReadWriteTransaction)(nil).SpannerReadOnlyTransaction))
}
