name: Secret Scanning

on:
  pull_request:
    types: [opened, synchronize, reopened] # these are the defaults - synchronize means 'commits pushed to PR'

jobs:
  trufflehog-secret-scanning:
    uses: cccteam/github-workflows/.github/workflows/secrets-scanning.yml@v5.9.0
